name: rhyme-with-ai
channels:
  - defaults
  - conda-forge
  - https://conda.anaconda.org/t/6N-MsQ4WZ7jo/soumith
dependencies:
  - ipykernel
  - python=3.7
  - torchvision
  - pip
  - pip:
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.5/en_core_web_sm-2.2.5.tar.gz
    - GitPython
    - pathtools
    - Pillow==6.1.0
    - streamlit
    - jupyter-server-proxy 
    - nbserverproxy
    - datetime
    - transformers
    - torch
    - fastai
    - numpy
    - scipy
    - joblib    
    - pandas
    - pandas-profiling
    - tweepy    
    - spacy
    - sklearn
    - plotly
    - matplotlib
    - seaborn
    - joblib
    - termcolor
    - hvplot
    - bokeh
    - holoviews
    - scikit-learn
    - altair
    - python-decouple
    - sqlalchemy
    - psycopg2
