name: rhyme-with-ai
channels:
  - defaults
  - conda-forge
  - https://conda.anaconda.org/t/6N-MsQ4WZ7jo/soumith
dependencies:
  - ipykernel
  - python=3.7
  - torch
  - torchvision
  - pip
  - pip:
    - GitPython
    - pathtools
    - Pillow==6.1.0
    - streamlit
    - jupyter-server-proxy 
    - nbserverproxy
    - fastai
    - numpy
    - pandas
    - pandas-profiling
    - sklearn
    - plotly
    - matplotlib
    - seaborn
    - joblib
    - termcolor
    - scikit-learn
